//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalHome.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceDetail
    {
        public int id { get; set; }
        public string ServiceName { get; set; }
        public string Description { get; set; }
    }
}
